### ISSUE TITLE
Does this extension need to exist?

### ISSUE THREAD

**Issue by Axlefublr** [cliffordfajardo/highlight-line-vscode#12]
`"editor.renderLineHighlight": "gutter"`

Check out this setting. Vs code lets you choose how to highlight the line your cursor is currently on

It's also highlighted in the minimap, so you'll know where your cursor is even if it's not currently on screen

**Comment by Axlefublr** [comment]
![image](https://user-images.githubusercontent.com/101342105/188218614-6077fa3f-77bf-4f80-9530-b031e933e322.png)

![image](https://user-images.githubusercontent.com/101342105/188218643-ee47b343-6731-448d-98fa-f5a8034efafe.png)

you don't even have to guess what the other settings might be, you can click on the pencil button next to the setting

or the easier method of just searching for the setting in settings

![image](https://user-images.githubusercontent.com/101342105/188218787-1d4f5add-a1a4-490a-ab60-ddebf9c299ef.png)

**Comment by Axlefublr** [comment]
Now I'm not saying "Delete your extension immediately!", but this feels like a project birthed from desperation, maybe this will be the solution you'd like more, along with some others that are currently using your extension

**Comment by Axlefublr** [comment]
![image](https://user-images.githubusercontent.com/101342105/188219055-575ed4d8-af8e-47ae-914f-36f00a54c342.png)

You can also change the cursor itself: its style and animation, to make it more obvious and visible

**Comment by Technetium1** [comment]
There's not a color feature yet though

**Comment by Axlefublr** [comment]
You're not wrong, but this feels like a pretty bad solution to the problem to me

**Comment by Technetium1** [comment]
@Axlefublr If people like me cared much about how graceful the implementation is; we'd have already contributed upstream to make it a feature inside VSC. As long as it underlines where I am with an obnoxious color, then that indeed checks all the boxes for me, and probably most other people. As long as it's not a spyware extension, it's good enough for me :)

**Comment by Axlefublr** [comment]
Can't relate, but I see your point! Go ahead then :)
